archlinux-wallpaper:
  extension: .svg
  output: archlinux-wallpaper
hex:
  extension: .svg
  output: hex
lines:
  extension: .svg
  output: lines
palette:
  extension: .svg
  output: palette
sun:
  extension: .svg
  output: sun
